version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-server
    ports:
    - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=default123
      - DB_NAME=service
      - NODE_ENV=development
    depends_on:
      - database
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - user_network
  
  database:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: default123
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - user_network  

networks:
  user_network:
    driver: bridge